### ISSUE TITLE
take any input

### ISSUE THREAD

**Issue by tmcw** [Turfjs/turf-simplify#3]
This should

* Support multipolygons
* Support multilinestrings
* Support geometrycollections
* Passthrough for other types

**Comment by nevi-me** [comment]
@morganherlocker need help with this? I'm manually unbundling rings from a `MultiPolygon` feature, applying the algorithm to them, then merging them back into a feature. Or would there be a more performant way?

**Comment by morganherlocker** [comment]
@nevi-me any help would be greatly appreciated. The method you propose would be spot on.

**Comment by nevi-me** [comment]
@morganherlocker I'm working on this now, but depending on whether @frankrowe 's work on 084cc96b21ea5fae42ef937f4c6c7ff073826ff4 goes into master, I might have to change the code a bit. Or should I work directly on top of his commits?

**Comment by nevi-me** [comment]
This is resolved with the merge of #7
